### ETL - Loading Data

In [1]:
import pandas as pd

In [3]:
#exporting data from CSV
flights_airlines_df=pd.read_csv('https://flightsproject.s3.us-east-2.amazonaws.com/flights_city_names.csv')
flights_airlines_df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,IATA_Code_Marketing_Airline,Operating_Airline,Origin,OriginCityName,Dest,...,Cancelled,CancellationCode,CRSElapsedTime,ActualElapsedTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime
0,0,2021,1,2,6,DL,9E,CVG,"Cincinnati, OH",BOS,...,0.0,NaN,129.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2021,1,3,7,DL,9E,CVG,"Cincinnati, OH",BOS,...,0.0,NaN,129.0,117.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2021,1,4,1,DL,9E,CVG,"Cincinnati, OH",BOS,...,0.0,NaN,129.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2021,1,7,4,DL,9E,CVG,"Cincinnati, OH",BOS,...,0.0,NaN,117.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2021,1,8,5,DL,9E,CVG,"Cincinnati, OH",BOS,...,0.0,NaN,117.0,135.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10390184,618785,2022,7,1,5,UA,YX,ALB,"Albany, NY",EWR,...,0.0,NaN,72.0,74.0,0.0,0.0,18.0,0.0,0.0,NaN
10390185,618786,2022,7,1,5,UA,YX,AVL,"Asheville, NC",EWR,...,0.0,NaN,127.0,112.0,NaN,NaN,NaN,NaN,NaN,NaN
10390186,618787,2022,7,1,5,UA,YX,ALB,"Albany, NY",EWR,...,0.0,NaN,72.0,100.0,0.0,0.0,20.0,0.0,0.0,NaN
10390187,618788,2022,7,1,5,UA,YX,BNA,"Nashville, TN",EWR,...,0.0,NaN,150.0,165.0,0.0,0.0,43.0,0.0,0.0,NaN
10390188,618789,2022,7,1,5,UA,YX,BOS,"Boston, MA",EWR,...,0.0,NaN,92.0,96.0,0.0,0.0,183.0,0.0,0.0,1600.0

In [4]:
#exporting data from CSV
airlines_cat_df=pd.read_csv('https://flightsproject.s3.us-east-2.amazonaws.com/Airlines.csv')
airlines_cat_df

        Code                    Description
0        02Q                  Titan Airways
1        04Q             Tradewind Aviation
2        05Q            Comlux Aviation, AG
3        06Q  Master Top Linhas Aereas Ltd.
4        07Q            Flair Airlines Ltd.
...      ...                            ...
1566      ZW    Air Wisconsin Airlines Corp
1567      ZX                   Air Georgian
1568  ZX (1)                     Airbc Ltd.
1569      ZY         Atlantic Gulf Airlines
1570     ZYZ           Skyway Aviation Inc.

[1571 rows x 2 columns]

In [5]:
#in dictionary
abbr_companies = airlines_cat_df.set_index('Code')['Description'].to_dict()

In [6]:
abbr_companies

{'02Q': 'Titan Airways',
 '04Q': 'Tradewind Aviation',
 '05Q': 'Comlux Aviation, AG',
 '06Q': 'Master Top Linhas Aereas Ltd.',
 '07Q': 'Flair Airlines Ltd.',
 '09Q': 'Swift Air, LLC',
 '0BQ': 'DCA',
 '0CQ': 'ACM AIR CHARTER GmbH',
 '0GQ': 'Inter Island Airways, d/b/a Inter Island Air',
 '0HQ': 'Polar Airlines de Mexico d/b/a Nova Air',
 '0J': 'JetClub AG',
 '0JQ': 'Vision Airlines',
 '0LQ': 'Metropix UK, LLP.',
 '0MQ': 'Multi-Aero, Inc. d/b/a Air Choice One',
 '0OQ': 'Open Skies',
 '0Q': 'Flying Service N.V.',
 '0QQ': 'TAG Aviation (UK) Ltd.',
 '0RQ': 'TAG Aviation Espana S.L.',
 '0TQ': 'Corporatejets, XXI',
 '0UQ': 'Comlux Malta, Ltd.',
 '0VQ': 'Ocean Sky (UK) Limited',
 '0WQ': 'Avjet Corporation',
 '0YQ': 'Comlux Malta Ltd.',
 '10Q': 'Swiss Air Ambulance',
 '12Q': 'Unijet',
 '13Q': 'Chartright Air Inc.',
 '14Q': 'London Air Services Limited',
 '15Q': 'Air Alsie A/S',
 '16': 'PSA Airlines Inc.',
 '17': 'Piedmont Airlines',
 '17Q': 'Albinati Aeronautics SA',
 '1AQ': 'Charter Air Transport, Inc.',
 '1BQ': 'Dynamic Airways, LLC',
 '1DQ': 'Island Airlines LLC',
 '1EQ': 'KaiserAir, Inc.',
 '1FQ': 'Alsek Air',
 '1HQ': 'International Jet Management GmbH',
 '1I': 'Sky Trek International Airlines',
 '1IQ': 'Jet link AG',
 '1JQ': 'Exec Direct Aviation Services Limited',
 '1LQ': 'Bertelsmann Aviation GmbH',
 '1MQ': 'Twin Cities Air Service LLC',
 '1NQ': 'JSC The 224th Flight Unit State Airlines',
 '1PQ': 'Makani Kai Air Charters',
 '1QQ': 'City Wings Inc dba Seaflight',
 '1RQ': 'Sun Air Express LLC dba Sun Air International',
 '1SQ': 'Star Marianas Air Inc.',
 '1TQ': 'Rhoades Aviation dba Transair',
 '1UQ': 'Gainjet Aviation SA',
 '1VQ': 'Scott Air LLC dba Island Air Express',
 '1WQ': 'Ultimate JetCharters LLC dba Ultimate Air Shuttle',
 '1XQ': 'Dassault Falcon Service',
 '2E': 'Smokey Bay Air Inc.',
 '2F': 'Frontier Flying Service',
 '2K': 'Aerolineas Galapagos S A Aerogal',
 '2M': 'Midway Express Airlines',
 '2O': 'Island Air Service',
 '2R': 'Regal Air',
 '2T': 'Canada 3000 Airlines Ltd.',
 '2U': 'Valley Air Express Inc.',
 '37': 'Zeal 320',
 '3C': 'Regions Air, Inc.',
 '3F': 'Pacific Airways, Inc.',
 '3M': 'Silver Airways',
 '3S': 'AeroLogic GmbH',
 '3U': 'Sichuan Airlines Co Ltd.',
 '4B': 'Boutique Air',
 '4B (1)': 'Olson Air Service',
 '4C': 'Aerovias de Intergracian Regional',
 '4E': 'Tanana Air Service',
 '4E (1)': 'British Airtours Limited',
 '4H': 'Belize Trans Air',
 '4M': 'LAN Argentina',
 '4M (1)': 'Lan Dominica',
 '4N': 'Air North',
 '4O': 'ABC Aerolineas SA de CV dba Interjet',
 '4R': 'Regent Air Corporation',
 '4S': 'Sol Air (Aero Hunduras)',
 '4S (1)': 'Conner Air Lines Inc.',
 '4T': 'Belair Airlines Ltd.',
 '4W': 'Warbelow',
 '4Y': 'Yute Air Aka Flight Alaska',
 '5B': 'Bellair Inc.',
 '5C': 'C.A.L Cargo Airlines',
 '5D': 'Aerolitoral',
 '5F': 'Arctic Circle Air Service',
 '5G': 'Skyservice Airlines, Inc.',
 '5G (1)': 'Queen Air',
 '5J': 'Private Jet Expeditions',
 '5L': 'Aerosur',
 '5V': 'Tatonduk Outfitters Limited d/b/a Everts Air Alaska and Everts Air Cargo',
 '5X': 'United Parcel Service',
 '5Y': 'Atlas Air Inc.',
 '6A': 'Aviacsa Airlines',
 '6B': 'TUIfly Nordic A.B.',
 '6C': 'Cape Smythe Air Service',
 '6F': 'Laker Airways Inc.',
 '6H': 'Israir Airlines',
 '6P': 'Pacific East Air Inc.',
 '6R': 'Aerounion Aerotransporte de Carga Union SA de CV',
 '6U': 'Air Ukraine',
 '6Y': 'Nicaraguense De Aviacion Sa',
 '7B': 'Krasair',
 '7C': 'Jeju Air Co Ltd.',
 '7F': 'First Air',
 '7G': 'MK Airlines Ltd.',
 '7G (1)': 'Bellair Inc. (1)',
 '7H': 'Era Aviation',
 '7I': 'Insel Air International B V',
 '7M': 'Aeromonterrey S.A.',
 '7N': 'Inland Aviation Services',
 '7P': 'Apa International Air S.A.',
 '7Q': 'Pan American World Airways Dominicana',
 '7S': 'Arctic Transportation',
 '7S (1)': 'Skystar International Inc.',
 '7Z': 'Lb Limited',
 '8C': 'Air Transport International',
 '8D': 'Servant Air Inc.',
 '8E': 'Bering Air Inc.',
 '8F': 'Wilburs Inc.',
 '8J': 'Jetall Airways',
 '8L': 'Servicio Aereo Leo Lopez',
 '8N': 'Flagship Airlines Inc.',
 '8Q': 'Baker Aviation Inc.',
 '8R': 'Edelweiss Air Ag',
 '8V': 'Wright Air Service',
 '9E': 'Endeavor Air Inc.',
 '9J': 'Pacific Island Aviation',
 '9K': 'Cape Air',
 '9L': 'Colgan Air',
 '9M': 'Central Mountain Air',
 '9N': 'ANA & JP Express Co. Ltd.',
 '9R': 'Flagship Express Services',
 '9S': 'Southern Air Inc.',
 '9T': 'TravelspanGT, Inc. S.A.',
 '9V': 'Avior Airlines, C.A.',
 '9W': 'Jet Airways (India) Limited',
 'A0': "Elysair d/b/a L'Avion",
 'A2': 'Cielos De Peru',
 'A4': 'Southern Wind Airlines',
 'A7': 'Air Comet S.A.',
 'A7 (1)': 'Air 21',
 'AA': 'American Airlines Inc.',
 'AAA': 'Associated Aviation Act.',
 'AAB': 'Antilles Air Boats Inc.',
 'AAE': 'AAA Airlines',
 'AAI': 'Audi Air Inc.',
 'AAL': 'Argosy Air Lines Inc.',
 'AAP': 'Armstrong Air Service Inc.',
 'AAQ': 'Advance Air Charters',
 'AAR': 'Altair Airlines Inc.',
 'AAT': 'Air Sunshine Inc.',
 'AAV': 'Alpine Air',
 'AAZ': 'Alaska Aeronautical Indust.',
 'AB': 'Air Berlin PLC and CO',
 'ABH': 'Air Bahia',
 'ABI': 'Airbama Incorporated',
 'ABO': 'Aeronaves Boringuena Inc.',
 'ABX': 'ABX Air, Inc.',
 'AC': 'Air Canada',
 'ACA': 'Alaska Central Airways Inc.',
 'ACD': 'Academy Airlines',
 'ACG': 'Air Cargo Express Inc.',
 'ACH': 'Island Airlines Hawaii Inc.',
 'ACI': 'AAA-Action Air Carrier Inc.',
 'ACJ': 'Atlantic Coast Jet Inc.',
 'ACK': 'Air Central Inc.',
 'ACL': 'Check-Air Inc.',
 'ACN': 'Alliance Airlines',
 'ACO': 'Air Cargo Enterprises Inc.',
 'ACP': 'Air Chaparral Inc.',
 'ACQ': 'Aeronautica De Cancun',
 'ACS': 'Alamo Commuter Airlines',
 'ACT': 'Air Central Inc. (1)',
 'ACW': 'Transwest Air Express',
 'AD': 'Avia Leasing Company',
 'ADB': 'Antonov Company',
 'ADQ': 'Aeronaves Del Peru',
 'ADR': 'Adirondack Airlines',
 'ADV': 'Advantage Airlines',
 'AE': 'Air Europe Limited',
 'AEC': 'Astec Air East Inc.',
 'AED': 'Air East Of Delaware Inc.',
 'AEF': 'Aero Freight',
 'AEO': 'Aero Coach',
 'AEQ': 'Air Caravane Inc.',
 'AEX': 'Air Excursions LLC (1)',
 'AF': 'Compagnie Natl Air France',
 'AFA': 'American Flag Airlines Inc.',
 'AFE': 'Air Florida Express',
 'AFG': 'American Flight Group',
 'AFQ': 'Aero B Venezuela C.A.',
 'AFS': 'Arcata Flying Service',
 'AGA': 'Air Cargo America Inc.',
 'AGQ': 'Argo S. A.',
 'AHA': 'Air Alpha',
 'AHC': 'Air Hawaii',
 'AHQ': 'Air National',
 'AI': 'National Aviation Company of India Limited d/b/a Air India',
 'AIA': 'All Island Air',
 'AIC': 'Air Caribbean',
 'AIE': 'Air Express Inc.',
 'AIG': 'Airgo Inc.',
 'AIK': 'Air Ketchum Idaho Inc.',
 'AIM': 'Air Mont. Inc.',
 'AIN': 'Air Indiana',
 'AIQ': 'Norontair',
 'AIT': 'Airways International',
 'AIY': 'Alliance Air',
 'AJ': 'Air Micronesia Inc.',
 'AJQ': 'Aerodynamics Inc.',
 'AKQ': 'Airmark Airlines Inc.',
 'AL': 'Skyway Airlines',
 'ALD': 'Allied Airlines',
 'ALE': 'Air-Lift Associates Inc.',
 'ALI': 'Brandt Air',
 'ALK': 'Air Link Airways',
 'ALL': 'All Seasons Air Pacific',
 'ALQ': 'Alberta Northern Airlines',
 'ALS': 'Air L.A.',
 'ALT': 'Altus Airlines',
 'ALU': 'Aleutian Air',
 'ALX': 'Atlanta Express',
 'AM': 'Aeromexico',
 'AMA': 'North American Airlines Inc.',
 'AME': 'Americair Inc.',
 'AMI': 'American Inter-Island Inc.',
 'AMQ': 'Ameristar Air Cargo',
 'AMR': 'AvAir',
 'AMT': 'American Air Transport',
 'ANB': 'Air Nebraska Inc.',
 'ANC': 'Atlantic Air',
 'AND': 'Southcentral Air Inc.',
 'ANI': 'Dash Air Corporation',
 'ANM': 'Airways Of New Mexico Inc.',
 'ANO': 'Metro Air Northeast Vermont',
 'ANT': 'Air North/Nenana',
 'AO': 'Aviacion Y Comercio S.A.',
 'AOI': 'Trans New York',
 'AON': 'Action Airlines',
 'AOQ': 'Aerovias S.A.',
 'AOR': 'Air New Orleans',
 'APE': 'Air Cape',
 'APH': 'Alpha Air',
 'API': 'Arizona Pacific Inc.',
 'APL': 'Appalachian Flying Service',
 'APN': 'Aspen Airways Inc.',
 'APQ': 'Alas De Transporte International',
 'APS': 'Air Spirit Inc.',
 'APY': 'Air Polynesia Inc.',
 'AQQ': 'Air Charter (Safa)',
 'AR': 'Aerolineas Argentinas',
 'ARA': 'Air Resorts Airlines',
 'ARB': 'Air Caribe International',
 'ARD': 'Airlift International',
 'ARI': 'Arizona Aero Corp.',
 'ARM': 'Airmarc Airlines Inc.',
 'ARN': 'Arnold Aviation',
 'ARO': 'Air Oregon',
 'ARP': 'Airspur Helicopters Inc.',
 'ARQ': 'Aerovias Colombianas Arca',
 'ARR': 'Arrowhead Airways Inc.',
 'ARS': 'Air Sedona',
 'ARZ': 'Arizona Airways',
 'AS': 'Alaska Airlines Inc.',
 'ASC': 'Air South Inc.',
 'ASD': 'Amistad Airlines',
 'ASH': 'Air South',
 'ASI': 'Alpine Air Services Inc.',
 'ASN': 'Air Casino',
 'ASP': 'Asap Air Inc.',
 'ASQ': 'Aerosur (1)',
 'ASR': 'Astor Air',
 'AST': 'Astro Airways',
 'ASU': 'Air South (1)',
 'ASW': 'Sunrise Airlines Inc.',
 'AT': 'Royal Air Maroc',
 'ATH': 'Air Southeast',
 'ATN': 'Air Atlantic Airlines Inc.',
 'ATO': 'Pacific National Airways',
 'ATQ': 'Aero Tranportes Panamenos',
 'ATS': 'Atlantis Airlines Inc.',
 'ATT': 'Aerotransit Inc.',
 'ATX': 'Air Carolina',
 'AUX': 'Austin Express Inc.',
 'AV': 'Aerovias Nacl De Colombia',
 'AVA': 'Air Vectors Airways',
 'AVC': 'Av Center Inc.',
 'AVG': 'Airvantage',
 'AVI': 'Aero Virgin Islands Corp.',
 'AVL': 'Aviation Sales',
 'AVQ': 'Aero Laguna S.A. De C.V.',
 'AVR': 'Air Vermont Inc.',
 'AVS': 'Aviation Services',
 'AVZ': 'Southern Jersey Airways',
 'AWA': 'Air West Airlines',
 'AWQ': 'Aermediterranea S.P.A.',
 'AX': 'Trans States Airlines',
 'AXQ': 'Aeron International Airlines Inc.',
 'AY': 'Finnair Oy',
 'AYQ': 'Aerodan S.A. De C.V.',
 'AZ': 'Compagnia Aerea Italiana',
 'AZP': 'Arizona Pacific Airways',
 'AZQ': 'Anglo Airlines Ltd.',
 'B6': 'JetBlue Airways',
 'BA': 'British Airways Plc',
 'BAA': 'Aero International Airlines',
 'BAC': 'Business Aircraft Corp.',
 'BAH': 'Brennan & Hargreaves Inc.',
 'BAK': 'Bankair Inc.',
 'BAN': 'Bangor International Air',
 'BAQ': 'Aero Rentas De Coahuila S.A. De C.V.',
 'BAR': 'Bard-Air Corp.',
 'BAT': 'West Penn Commuter',
 'BAY': 'Burlington Aeroplane Co.',
 'BBQ': 'Balair Ag',
 'BC': 'Skymark Airlines Inc.',
 'BCA': 'Baja Cortez Airlines',
 'BCQ': 'Bradley Air Services Ltd.',
 'BD': 'British Midland Airways Ltd.',
 'BDE': 'Jet Express',
 'BDQ': 'Aerotaxis De Aguascalientes S.A. De C.V.',
 'BE': 'Braniff International Airlines Inc.',
 'BEA': 'Business Express Airlines',
 'BEN': 'Bennington Aviation Inc.',
 'BEQ': 'Air Belgium',
 'BES': 'Aeroservices Executive',
 'BEY': 'Beyer Aviation',
 'BF': 'Markair Inc.',
 'BFG': 'Million Air',
 'BFQ': 'Buffalo Airways Inc.',
 'BG': 'Biman Bangladesh Airlines',
 'BGQ': "Airbus Transport Internat'l",
 'BHK': 'Blackhawk Airways Inc.',
 'BHO': 'Bighorn Airways Inc.',
 'BHQ': 'Turks Air Ltd. (1)',
 'BIA': 'Big Island Air',
 'BIQ': 'Servicios Aeronauticos Z S.A. De C.V.',
 'BIR': 'Birchwood Air Service',
 'BJQ': 'Taxirey S.A. De C.V.',
 'BLQ': 'Air Bvi Limited',
 'BM': 'Belize Air International Ltd.',
 'BMT': 'Bremerton Aviation Inc.',
 'BN': 'Britannia Airways GmbH',
 'BN (1)': 'Braniff Inc.',
 'BNQ': 'NetJets Large Aircraft Company L.L.C.',
 'BOA': 'Boise Air Service',
 'BOI': 'Bo-S-Aire Airlines Inc.',
 'BOQ': 'Transp. Aereos Bolivianos',
 'BQ': 'Aeromar C. Por A.',
 'BR': 'Eva Airways Corporation',
 'BR (1)': 'Cal Air International Ltd.',
 'BRK': 'Barken International',
 'BRO': 'Brower Airways Inc.',
 'BRW': 'Barrow Air',
 'BTQ': 'Brasair Transportes Aereos',
 'BUH': 'Business Helicopters',
 'BUQ': 'Wrangler Aviation Inc.',
 'BUQ (1)': 'Blue Bell Inc.',
 'BUR': 'Burlington Airways Inc.',
 'BW': 'Caribbean Airlines Limited',
 'BXQ': 'Spantax S. A.',
 'BY': 'Britannia Airways Ltd.',
 'BYA': 'Bay Air',
 'BZQ': 'Abaco Air, Ltd.',
 'C5': 'Commutair Aka Champlain Enterprises, Inc.',
 'C6': 'Canjet Airlines',
 'C8': 'Cargolux Italia SpA',
 'C8 (1)': 'Chicago Express Airlines',
 'CA': 'Air China',
 'CAC': 'Coleman Air Transport',
 'CAF': 'California Seaboard',
 'CAI': 'Crawford Aviation Inc.',
 'CAM': 'C & M Airlines',
 'CAP': 'Metro Air Northeast N Y',
 'CAQ': 'Challenge Air Luftverkehrs GmbH',
 'CAT': 'Catalina Airlines Inc.',
 'CAV': 'Air Virginia',
 'CAZ': 'CAT Aviation',
 'CB': 'Air One Inc.',
 'CBA': 'Carriba Air Inc.',
 'CC': 'Air Atlanta Icelandic',
 'CC (1)': 'Air Atlanta Inc.',
 'CCA': 'Cityhop',
 'CCO': 'Chester County Aviation',
 'CDQ': 'Kitty Hawk International',
 'CEN': 'Cen-Tex Airlines Inc.',
 'CEQ': 'All Canada Express',
 'CET': 'Century Airlines (Cal)',
 'CF': 'Compan. De Aviacion Faucett',
 'CGA': 'Chicago Airlines',
 'CGL': 'Viking International Airlines Inc.',
 'CGO': 'Chicago Air Taxi',
 'CH': 'Bemidji Airlines',
 'CHD': 'Chandler Flyer',
 'CHE': 'Charter Airlines',
 'CHF': 'Hammonds Commuter Air Serv.',
 'CHI': 'Chitina Air Service',
 'CHL': 'Channel Flying Inc.',
 'CHO': 'Choi Aviation Inc.',
 'CHS': 'Christman Air System',
 'CHT': 'Charter One',
 'CI': 'China Airlines Ltd.',
 'CIQ': 'A/S Conair',
 'CIS': 'Cal Sierra Airlines',
 'CJ': 'Colgan Airways Inc.',
 'CK': 'China Cargo Airline',
 'CKI': 'Inlet Airlines',
 'CL': 'Capitol International Inc.',
 'CLB': 'Columbia Pacific Airlines',
 'CLD': 'Hawaii Pacific Helicopters',
 'CLF': 'California Air Shuttle',
 'CLQ': 'Aero Transcolombiana',
 'CM': 'Compania Panamena (Copa)',
 'CMB': 'Combs Airways Inc.',
 'CMD': 'Command Airways Inc.',
 'CMQ': 'Servicio De Carga Aerea Sa',
 'CMR': 'Commuter Airlines (Ca)',
 'CNN': 'Centennial Airlines',
 'CO': 'Continental Air Lines Inc.',
 'COB': 'Cotton Belt Aviation Inc.',
 'COC': 'Cochise Airlines Inc.',
 'COK': 'Coker Aviation Inc.',
 'COL': 'Presidential Express',
 'COM': 'Commutair',
 'COR': 'Coral Air Inc.',
 'COS': 'Cosmopolitan Comm. Airline',
 'COT': 'Southeastern Commuter',
 'COU': 'Courtesy Air Service Inc.',
 'CP': 'Compass Airlines',
 'CP (1)': 'Canadian Airlines International Ltd.',
 'CPA': 'Capitol Air Lines',
 'CPC': 'Coastal Plains Commuter Inc.',
 'CPQ': 'Capitol Air Express Inc.',
 'CPT': 'Capitol Air',
 'CQI': 'Conquest Airline Corp.',
 'CRA': 'Commuter Airlines',
 'CRB': 'Caribair',
 'CRE': 'Caribbean Express Inc.',
 'CRH': 'Cresent Medivac',
 'CRN': 'Crown Aviaiton Inc.',
 'CRO': 'Crown Airways Inc.',
 'CRP': 'Corporate Air',
 'CRT': 'Crested Butte Air Service',
 'CRV': 'Acropolis Aviation Ltd.',
 'CS': 'Continental Micronesia',
 'CSA': 'Casino Airlines',
 'CSK': 'Catskill Airways Inc.',
 'CSL': 'Central States Air Lines',
 'CSM': 'Chisum Flying Service',
 'CSN': 'Casino Airlines (1)',
 'CSQ': 'Celtic Tech Jet Ltd.',
 'CTA': 'Century Airlines',
 'CTH': 'Cothron Aviation',
 'CTL': 'Coastal Air Transport',
 'CTQ': 'Custom Air Transport',
 'CTR': 'Chartair',
 'CUQ': 'Caicos Caribbean Airways',
 'CUS': 'Custom Air Service',
 'CV': 'Cargolux Airlines International S.A',
 'CVA': 'Catalina-Vegas Airlines',
 'CVQ': 'Caraven S.A.',
 'CW': 'Air Marshall Islands Inc.',
 'CWQ': 'Canadian Aviation Express',
 'CX': 'Cathay Pacific Airways Ltd.',
 'CYQ': 'Corse Air International',
 'CZ': 'China Southern Airlines',
 'CZ (1)': 'Cascade Airways Inc.',
 'CZQ': 'Aviation Concepts',
 'DA': 'Dan Air Services',
 'DAN': 'Danbury Airlines',
 'DAU': 'Dauphin Island Airways',
 'DC': 'Caribbean Air Cargo Co Ltd.',
 'DE': 'Condor Flugdienst',
 'DEA': 'Downeast Airlines Inc.',
 'DEC': 'Decatur Aviation',
 'DFS': 'Downeast Flying Service',
 'DH': 'Independence Air',
 'DH (1)': 'Discovery Airways Inc.',
 'DHL': 'DHL Airlines Inc.',
 'DHQ': 'DHL Aero Expresso',
 'DIA': 'Drummond Island Air',
 'DIC': 'Dickman Aviation Services',
 'DIR': 'Northern Star',
 'DL': 'Delta Air Lines Inc.',
 'DM': 'Maersk Air I/S',
 'DO': 'Compania Dominicana De Avia',
 'DOL': 'Dolphin Airways Inc.',
 'DOQ': 'Aerolineas Dominicanas S A',
 'DPA': 'Desert Pacific Airways',
 'DPI': 'Desert Pacific Airlines Inc.',
 'DQQ': 'Caribwest Airways Ltd.',
 'DSA': 'Desert Sun Airlines',
 'DST': 'Desert Airlines',
 'DUL': 'Dulles Express',
 'DUZ': 'Summit Airlines Inc.',
 'DVO': 'Devoe Airlines',
 'DWN': 'Dawn Air',
 'DXA': 'Dolphin Express',
 'DY': 'Norwegian Air Shuttle ASA',
 'E0': 'EOS Airlines, Inc.',
 'E7': 'Estafeta Carga Aereas',
 'E72': 'European Aviation Air Charter',
 'E8': 'USAfrica Airways Inc.',
 'E9': 'Boston-Maine Airways',
 'EA': 'Eastern Air Lines Inc.',
 'EAI': 'Executive Aviation Inc.',
 'EAQ': 'Executive Airlines, SL',
 'EAS': 'Eastern Caribbean Airways',
 'EAT': 'Eastman Airways Inc.',
 'EBQ': 'Execaire Aviation Ltd.',
 'ECA': 'Eagle Airlines (1)',
 'ECI': 'Eastern Carolina Aviation',
 'ECL': 'Eclipse Airlines',
 'ECQ': 'Trans American Charter',
 'ECR': 'East Coast Airways',
 'ED': 'Andes',
 'EDE': 'Ede Aire',
 'EET': 'Exec Express II',
 'EEX': 'Exec Express',
 'EEZ': 'Eagle Aviation Inc.',
 'EFA': 'Executive Four Winds',
 'EFQ': 'Trans Europ. Airways France',
 'EGA': 'Eagle Airline',
 'EGJ': 'Eagle Jet Charter',
 'EGL': 'Eagle Commuter Airlines Inc.',
 'EH': 'Saeta Airlines',
 'EHA': 'East Hampton Aire Inc.',
 'EI': 'Aer Lingus Plc',
 'EIA': 'East. Indiana Aviation Sale',
 'EJQ': 'Aeroejecutivos C.A.',
 'EK': 'Emirates',
 'EKA': 'Air Pacific Inc.',
 'ELL': 'Ellis Air Taxi Inc.',
 'EM': 'Empire Airlines Inc.',
 'EMA': 'Emerald Airlines',
 'EME': 'Metro Express',
 'EMP': 'Empire Airlines Inc. (2)',
 'ENT': 'Enterprise Airlines Inc.',
 'EOQ': 'Aeroservicios Ecuatorianos',
 'EP': 'All Star Airlines Inc.',
 'EQ': 'Tame Linea Aerea del Ecuador Tme EP',
 'ER': 'Astar USA, LLC',
 'ERI': 'Erie Airways Inc.',
 'ERO': 'Empire Aero Service',
 'ERQ': 'Aero Trades (Western) Ltd.',
 'ESQ': 'Seagreen Air Transport',
 'ET': 'Ethiopian Airlines',
 'EU': 'Ecuatoriana De Aviacion',
 'EUQ': 'Air Atlanta Europe',
 'EV': 'ExpressJet Airlines Inc.',
 'EVA': 'Evanston Aviation',
 'EWA': 'Rio Grande Air',
 'EXA': 'Columbia Pacific Airlines (1)',
 'EXC': 'Hapag-Lloyd Executive GmbH',
 'EXC (1)': 'Executive Charter',
 'EXP': 'Express Airlines II',
 'EXQ': 'Export Air Del Peru S.A.',
 'EXR': 'Executive Transport',
 'EY': 'Etihad Airways',
 'EZ': 'Evergreen International Inc.',
 'F2': 'Omega Air Holdings d/b/a Focus Air',
 'F8': 'Freedom Airlines d/b/a HP Expr',
 'F9': 'Frontier Airlines Inc.',
 'FAA': 'Falwell Aviation Inc.',
 'FAC': 'Falcon Airways Inc.',
 'FAQ': 'Fast Air Carrier Ltd. (1)',
 'FAR': 'Federal Armored Service Inc.',
 'FB': 'Translift Airways Limited',
 'FBI': 'Young Flying Service',
 'FCA': 'Southern Airlines Inc.',
 'FCQ': 'Falcon Air Express',
 'FD': 'Air Puerto Rico Airlines',
 'FDA': 'Florida Airlines Inc.',
 'FDM': 'Freedom Airlines Inc.',
 'FDQ': 'Great American Airways',
 'FE': 'Primaris Airlines Inc.',
 'FF': 'Tower Air Inc.',
 'FFQ': 'Five Star Airlines',
 'FH': 'Frontier Horizon Inc.',
 'FI': 'Icelandair',
 'FJ': 'Air Pacific Ltd.',
 'FJ (1)': 'Air Pacific Ltd. (1)',
 'FL': 'AirTran Airways Corporation',
 'FL (1)': 'Frontier Airlines Inc. (1)',
 'FLA': 'Florida Air',
 'FLM': 'Flamenco Airways Inc.',
 'FLR': 'Flirite Inc.',
 'FNQ': 'Fine Airlines Inc.',
 'FOR': 'Ford-Aire Inc.',
 'FOS': 'Foster Aviation',
 'FP': 'TAG Aviation S.A.',
 'FQ': 'Air Aruba',
 'FRA': 'Freedom Air',
 'FRS': 'Four Star Aviation',
 'FRT': 'Frontier Commuter',
 'FRW': 'Farwest Airlines',
 'FS': 'Serv De Trans Aereos Fuegui',
 'FSA': 'F.S. Air Service',
 'FT': 'Flying Tiger Line Inc.',
 'FTI': 'Southern Airways',
 'FVA': 'Skycraft Inc.',
 'FW': 'Skybus Inc.',
 'FWA': 'Far West Airlines',
 'FX': 'Federal Express Corporation',
 'FYB': 'Flying Boat',
 'G3': 'VRG Linhas Aereas S A',
 'G3 (1)': 'Aerochago S.A.',
 'G4': 'Allegiant Air',
 'G7': 'GoJet Airlines, LLC d/b/a United Express',
 'GA': 'P.T. Garuda Indonesian Arwy',
 'GAL': 'Galena Air Service',
 'GAQ': 'Galaxy Airlines Inc.',
 'GAS': 'General Aviation Inc.',
 'GAT': 'Gulf Air Taxi',
 'GAV': 'Gromer Aviation Inc.',
 'GBA': 'Central States Airline',
 'GBQ': 'G5 Executive Ag',
 'GCA': 'Golden Carriage Aire',
 'GCH': 'Grand Canyon Helicopters',
 'GCQ': 'General Air Cargo',
 'GCS': 'Midway Commuter',
 'GD': 'Transp. Aereos Ejecutivos',
 'GDW': 'Golden West Airlines Inc.',
 'GE': 'Lufthansa Cargo Airlines',
 'GF': 'Gulf Air Company',
 'GF (1)': 'Gulf Air Transport Inc.',
 'GFC': 'Gulf Flite Center',
 'GFQ': 'Gulf And Caribbean Cargo',
 'GG': 'Cargo 360, Inc.',
 'GG (1)': 'Tropical Airways Inc.',
 'GG (2)': 'Grenada Airways Ltd.',
 'GH': 'Ghana Airways Corporation',
 'GHA': 'Green Hills Aviation Ltd.',

In [11]:
# I extract a subset of columns and redefine the airlines labeling 
flights_name_df = airlines_cat_df.loc[:, ['Description']]
flights_name_df['Description'] = flights_name_df['Description'].replace(abbr_companies)

In [12]:
flights_name_df

                        Description
0                     Titan Airways
1                Tradewind Aviation
2               Comlux Aviation, AG
3     Master Top Linhas Aereas Ltd.
4               Flair Airlines Ltd.
...                             ...
1566    Air Wisconsin Airlines Corp
1567                   Air Georgian
1568                     Airbc Ltd.
1569         Atlantic Gulf Airlines
1570           Skyway Aviation Inc.

[1571 rows x 1 columns]

In [15]:
#rename code
#abbr_companies = airlines_cat_df.set_index('Code')['Description'].to_dict()
airlines_cat_df.rename(columns = {'Code':'IATA_Code_Marketing_Airline'}, inplace = True)
airlines_cat_df

     IATA_Code_Marketing_Airline                    Description
0                            02Q                  Titan Airways
1                            04Q             Tradewind Aviation
2                            05Q            Comlux Aviation, AG
3                            06Q  Master Top Linhas Aereas Ltd.
4                            07Q            Flair Airlines Ltd.
...                          ...                            ...
1566                          ZW    Air Wisconsin Airlines Corp
1567                          ZX                   Air Georgian
1568                      ZX (1)                     Airbc Ltd.
1569                          ZY         Atlantic Gulf Airlines
1570                         ZYZ           Skyway Aviation Inc.

[1571 rows x 2 columns]

In [16]:
airlines_cat_df.rename(columns = {'Description':'Airline'}, inplace = True)
airlines_cat_df

     IATA_Code_Marketing_Airline                        Airline
0                            02Q                  Titan Airways
1                            04Q             Tradewind Aviation
2                            05Q            Comlux Aviation, AG
3                            06Q  Master Top Linhas Aereas Ltd.
4                            07Q            Flair Airlines Ltd.
...                          ...                            ...
1566                          ZW    Air Wisconsin Airlines Corp
1567                          ZX                   Air Georgian
1568                      ZX (1)                     Airbc Ltd.
1569                          ZY         Atlantic Gulf Airlines
1570                         ZYZ           Skyway Aviation Inc.

[1571 rows x 2 columns]

In [18]:
#merge
flights_merged_df = flights_airlines_df.merge(airlines_cat_df,on=["IATA_Code_Marketing_Airline"])
flights_merged_df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,IATA_Code_Marketing_Airline,Operating_Airline,Origin,OriginCityName,Dest,...,CancellationCode,CRSElapsedTime,ActualElapsedTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,Airline
0,0,2021,1,2,6,DL,9E,CVG,"Cincinnati, OH",BOS,...,NaN,129.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
1,1,2021,1,3,7,DL,9E,CVG,"Cincinnati, OH",BOS,...,NaN,129.0,117.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
2,2,2021,1,4,1,DL,9E,CVG,"Cincinnati, OH",BOS,...,NaN,129.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
3,3,2021,1,7,4,DL,9E,CVG,"Cincinnati, OH",BOS,...,NaN,117.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
4,4,2021,1,8,5,DL,9E,CVG,"Cincinnati, OH",BOS,...,NaN,117.0,135.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10390184,582498,2022,7,25,1,WN,WN,ORD,"Chicago, IL",BWI,...,A,110.0,NaN,NaN,NaN,NaN,NaN,NaN,1310.0,Southwest Airlines Co.
10390185,582499,2022,7,26,2,WN,WN,BWI,"Baltimore, MD",HOU,...,NaN,190.0,184.0,22.0,0.0,0.0,0.0,6.0,NaN,Southwest Airlines Co.
10390186,582500,2022,7,26,2,WN,WN,MIA,"Miami, FL",AUS,...,NaN,175.0,272.0,35.0,0.0,97.0,0.0,5.0,NaN,Southwest Airlines Co.
10390187,582501,2022,7,26,2,WN,WN,MIA,"Miami, FL",MDW,...,NaN,190.0,203.0,0.0,0.0,269.0,0.0,6.0,1207.0,Southwest Airlines Co.
10390188,582502,2022,7,29,5,WN,WN,LAS,"Las Vegas, NV",DEN,...,NaN,115.0,224.0,9.0,0.0,109.0,0.0,6.0,NaN,Southwest Airlines Co.

In [30]:
flights_data_df = flights_merged_df.drop(['Unnamed: 0', 'IATA_Code_Marketing_Airline', 'Operating_Airline '], axis = 1)
flights_data_df

,Year,Month,DayofMonth,DayOfWeek,Origin,OriginCityName,Dest,DestCityName,CRSDepTime,DepTime,...,CancellationCode,CRSElapsedTime,ActualElapsedTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,Airline
0,2021,1,2,6,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,733.0,...,NaN,129.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
1,2021,1,3,7,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,727.0,...,NaN,129.0,117.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
2,2021,1,4,1,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,737.0,...,NaN,129.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
3,2021,1,7,4,CVG,"Cincinnati, OH",BOS,"Boston, MA",1715,1710.0,...,NaN,117.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
4,2021,1,8,5,CVG,"Cincinnati, OH",BOS,"Boston, MA",1715,1711.0,...,NaN,117.0,135.0,NaN,NaN,NaN,NaN,NaN,NaN,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10390184,2022,7,25,1,ORD,"Chicago, IL",BWI,"Baltimore, MD",1235,1310.0,...,A,110.0,NaN,NaN,NaN,NaN,NaN,NaN,1310.0,Southwest Airlines Co.
10390185,2022,7,26,2,BWI,"Baltimore, MD",HOU,"Houston, TX",2145,2219.0,...,NaN,190.0,184.0,22.0,0.0,0.0,0.0,6.0,NaN,Southwest Airlines Co.
10390186,2022,7,26,2,MIA,"Miami, FL",AUS,"Austin, TX",1610,1650.0,...,NaN,175.0,272.0,35.0,0.0,97.0,0.0,5.0,NaN,Southwest Airlines Co.
10390187,2022,7,26,2,MIA,"Miami, FL",MDW,"Chicago, IL",1210,1632.0,...,NaN,190.0,203.0,0.0,0.0,269.0,0.0,6.0,1207.0,Southwest Airlines Co.
10390188,2022,7,29,5,LAS,"Las Vegas, NV",DEN,"Denver, CO",1830,1845.0,...,NaN,115.0,224.0,9.0,0.0,109.0,0.0,6.0,NaN,Southwest Airlines Co.

In [32]:
cols = list(flights_data_df.columns.values)
cols

['Year',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'Origin',
 'OriginCityName',
 'Dest',
 'DestCityName',
 'CRSDepTime',
 'DepTime',
 'DepDelayMinutes',
 'CRSArrTime',
 'ArrTime',
 'Cancelled',
 'CancellationCode',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'Airline']

In [33]:
flights_data_df = flights_data_df[['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'Airline', 'Origin', 'OriginCityName', 'Dest', 'DestCityName', 'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'CRSArrTime' ,'ArrTime', 'Cancelled', 'CancellationCode', 'CRSElapsedTime', 'ActualElapsedTime', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay', 'FirstDepTime']]
flights_data_df

,Year,Month,DayofMonth,DayOfWeek,Airline,Origin,OriginCityName,Dest,DestCityName,CRSDepTime,...,Cancelled,CancellationCode,CRSElapsedTime,ActualElapsedTime,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime
0,2021,1,2,6,Delta Air Lines Inc.,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,...,0.0,NaN,129.0,114.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,1,3,7,Delta Air Lines Inc.,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,...,0.0,NaN,129.0,117.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,1,4,1,Delta Air Lines Inc.,CVG,"Cincinnati, OH",BOS,"Boston, MA",730,...,0.0,NaN,129.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,1,7,4,Delta Air Lines Inc.,CVG,"Cincinnati, OH",BOS,"Boston, MA",1715,...,0.0,NaN,117.0,121.0,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,1,8,5,Delta Air Lines Inc.,CVG,"Cincinnati, OH",BOS,"Boston, MA",1715,...,0.0,NaN,117.0,135.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10390184,2022,7,25,1,Southwest Airlines Co.,ORD,"Chicago, IL",BWI,"Baltimore, MD",1235,...,1.0,A,110.0,NaN,NaN,NaN,NaN,NaN,NaN,1310.0
10390185,2022,7,26,2,Southwest Airlines Co.,BWI,"Baltimore, MD",HOU,"Houston, TX",2145,...,0.0,NaN,190.0,184.0,22.0,0.0,0.0,0.0,6.0,NaN
10390186,2022,7,26,2,Southwest Airlines Co.,MIA,"Miami, FL",AUS,"Austin, TX",1610,...,0.0,NaN,175.0,272.0,35.0,0.0,97.0,0.0,5.0,NaN
10390187,2022,7,26,2,Southwest Airlines Co.,MIA,"Miami, FL",MDW,"Chicago, IL",1210,...,0.0,NaN,190.0,203.0,0.0,0.0,269.0,0.0,6.0,1207.0
10390188,2022,7,29,5,Southwest Airlines Co.,LAS,"Las Vegas, NV",DEN,"Denver, CO",1830,...,0.0,NaN,115.0,224.0,9.0,0.0,109.0,0.0,6.0,NaN

In [34]:
flights_data_df.to_csv('flights_data_df.csv')